version: '2'
# services:
#   web:
#     build: ./src
#     ports:
#      - "4265:8080"
#     volumes:
#      - ./src:/code
services: 
  weba:
    build: .
    expose:
      - 8080

  webb:
    build: .
    expose:
      - 8080

  webc:
    build: .
    expose:
      - 8080
  lb:
    image: haproxy:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - weba
      - webb
      - webc
    ports:
      - "80:80"
      - "70:70"

    expose:
      - "80"
      - "70"
