version: '3'
# services:
#   web:
#     build: ./src
#     ports:
#      - "4265:8080"
#     volumes:
#      - ./src:/code
services: 
  api1:
    build: .
    volumes: 
      - .:/code
    expose:
      - 8080

  api2:
    build: .
    volumes: 
      - .:/code
    expose:
      - 8080
  lb:
    image: haproxy:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - api1
      - api2
    ports:
      - "8080:8080"
    expose:
      - "8080"
